/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--md-sys-color-background)',
        surface: 'var(--md-sys-color-surface)',
        'on-surface': 'var(--md-sys-color-on-surface)',
        'surface-variant': 'var(--md-sys-color-surface-variant)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'surface-container-low': 'var(--md-sys-color-surface-container-low)',
        'surface-container': 'var(--md-sys-color-surface-container)',
        'surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
        outline: 'var(--md-sys-color-outline)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        'on-primary': 'var(--md-sys-color-on-primary)',
        'primary-container': 'var(--md-sys-color-primary-container)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        'on-secondary': 'var(--md-sys-color-on-secondary)',
        'secondary-container': 'var(--md-sys-color-secondary-container)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        error: 'var(--md-sys-color-error)',
        'on-error': 'var(--md-sys-color-on-error)',
        'error-container': 'var(--md-sys-color-error-container)',
        'on-error-container': 'var(--md-sys-color-on-error-container)',
        success: 'var(--md-sys-color-success)',
        'success-container': 'var(--md-sys-color-success-container)',
        'on-success-container': 'var(--md-sys-color-on-success-container)',
        warning: 'var(--md-sys-color-warning)',
        'warning-container': 'var(--md-sys-color-warning-container)',
        'on-warning-container': 'var(--md-sys-color-on-warning-container)',
        scrim: 'var(--md-sys-color-scrim)',
        focus: 'var(--md-sys-color-focus-ring)',
        'confidence-high': 'var(--md-ref-palette-confidence-high)',
        'confidence-mid': 'var(--md-ref-palette-confidence-mid)',
        'confidence-low': 'var(--md-ref-palette-confidence-low)',
        'confidence-track': 'var(--md-ref-palette-confidence-track)',
        white: 'var(--md-sys-color-surface)',
        gray: {
          50: 'var(--md-sys-color-surface-container-low)',
          100: 'var(--md-sys-color-surface-container)',
          200: 'var(--md-sys-color-outline-variant)',
          300: 'var(--md-sys-color-outline)',
          400: 'var(--md-sys-color-on-surface-variant)',
          500: 'var(--md-sys-color-on-surface-variant)',
          600: 'var(--md-sys-color-on-surface-variant)',
          700: 'var(--md-sys-color-on-surface)',
          800: 'var(--md-sys-color-on-surface)',
          900: 'var(--md-sys-color-on-surface)',
        },
        primary: {
          50: 'var(--md-sys-color-primary-container)',
          100: 'var(--md-sys-color-primary-container)',
          200: 'var(--md-sys-color-primary-container)',
          300: 'var(--md-sys-color-primary)',
          400: 'var(--md-sys-color-primary)',
          500: 'var(--md-sys-color-primary)',
          600: 'var(--md-sys-color-primary)',
          700: 'var(--md-sys-color-primary)',
          800: 'var(--md-sys-color-primary)',
          900: 'var(--md-sys-color-primary)',
        },
        slate: {
          50: 'var(--md-sys-color-surface-container-low)',
          100: 'var(--md-sys-color-surface-container-low)',
          200: 'var(--md-sys-color-outline-variant)',
          300: 'var(--md-sys-color-outline)',
          400: 'var(--md-sys-color-on-surface-variant)',
          500: 'var(--md-sys-color-on-surface-variant)',
          600: 'var(--md-sys-color-outline)',
          700: 'var(--md-sys-color-surface-container-high)',
          800: 'var(--md-sys-color-surface-container-high)',
          900: 'var(--md-sys-color-surface-container)',
          950: 'var(--md-sys-color-background)',
        },
        pink: {
          50: 'var(--md-sys-color-secondary-container)',
          100: 'var(--md-sys-color-secondary-container)',
          700: 'var(--md-sys-color-on-secondary-container)',
        },
        blue: {
          100: 'var(--md-sys-color-primary-container)',
          700: 'var(--md-sys-color-on-primary-container)',
        },
        red: {
          50: 'var(--md-sys-color-error-container)',
          200: 'var(--md-sys-color-error-container)',
          300: 'var(--md-sys-color-error)',
          500: 'var(--md-sys-color-error)',
          600: 'var(--md-sys-color-error)',
          700: 'var(--md-sys-color-on-error-container)',
        },
        green: {
          500: 'var(--md-sys-color-success)',
          600: 'var(--md-sys-color-success)',
        },
        yellow: {
          500: 'var(--md-sys-color-warning)',
          600: 'var(--md-sys-color-warning)',
        },
      },
      borderRadius: {
        xs: 'var(--md-sys-shape-corner-extra-small)',
        sm: 'var(--md-sys-shape-corner-small)',
        md: 'var(--md-sys-shape-corner-small)',
        lg: 'var(--md-sys-shape-corner-medium)',
        xl: 'var(--md-sys-shape-corner-large)',
        '2xl': 'var(--md-sys-shape-corner-extra-large)',
        button: 'var(--md-comp-button-container-shape)',
        card: 'var(--md-comp-card-container-shape)',
        field: 'var(--md-comp-field-container-shape)',
        chip: 'var(--md-comp-chip-container-shape)',
      },
      boxShadow: {
        sm: 'var(--md-sys-elevation-1)',
        md: 'var(--md-sys-elevation-2)',
        lg: 'var(--md-sys-elevation-3)',
        xl: 'var(--md-sys-elevation-4)',
        '2xl': 'var(--md-sys-elevation-5)',
      },
      fontFamily: {
        sans: 'var(--md-sys-typescale-font-family)',
      },
      spacing: {
        1: 'var(--md-sys-spacing-1)',
        2: 'var(--md-sys-spacing-2)',
        3: 'var(--md-sys-spacing-3)',
        4: 'var(--md-sys-spacing-4)',
        5: 'var(--md-sys-spacing-5)',
        6: 'var(--md-sys-spacing-6)',
        8: 'var(--md-sys-spacing-8)',
        10: 'var(--md-sys-spacing-10)',
        12: 'var(--md-sys-spacing-12)',
        16: 'var(--md-sys-spacing-16)',
        touch: 'var(--md-sys-touch-target-size)',
        button: 'var(--md-comp-button-container-height)',
        field: 'var(--md-comp-field-container-height)',
        chip: 'var(--md-comp-chip-container-height)',
      },
      transitionDuration: {
        short: 'var(--md-sys-motion-duration-short)',
        medium: 'var(--md-sys-motion-duration-medium)',
        long: 'var(--md-sys-motion-duration-long)',
      },
      transitionTimingFunction: {
        standard: 'var(--md-sys-motion-easing-standard)',
      },
      fontSize: {
        'display-large': [
          'var(--md-sys-typescale-display-large-size)',
          { lineHeight: 'var(--md-sys-typescale-display-large-line-height)', fontWeight: 'var(--md-sys-typescale-display-large-weight)' },
        ],
        'headline-large': [
          'var(--md-sys-typescale-headline-large-size)',
          { lineHeight: 'var(--md-sys-typescale-headline-large-line-height)', fontWeight: 'var(--md-sys-typescale-headline-large-weight)' },
        ],
        'title-large': [
          'var(--md-sys-typescale-title-large-size)',
          { lineHeight: 'var(--md-sys-typescale-title-large-line-height)', fontWeight: 'var(--md-sys-typescale-title-large-weight)' },
        ],
        'body-large': [
          'var(--md-sys-typescale-body-large-size)',
          { lineHeight: 'var(--md-sys-typescale-body-large-line-height)', fontWeight: 'var(--md-sys-typescale-body-large-weight)' },
        ],
        'label-large': [
          'var(--md-sys-typescale-label-large-size)',
          { lineHeight: 'var(--md-sys-typescale-label-large-line-height)', fontWeight: 'var(--md-sys-typescale-label-large-weight)' },
        ],
      },
    },
  },
  plugins: [],
}
